modLoader="javafml" #mandatory
loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
issueTrackerURL="https://github.com/USER/REPO/issues" #optional

[[mods]] #mandatory
modId="testung" #mandatory
version="1.0.0" #mandatory
displayName="testung" #mandatory
displayURL="https://github.com/USER/REPO" #optional
logoFile="examplemod.png" #optional
credits="Thanks for this mod" #optional
authors="Author" #optional
description='''
This is a placeholder description for the mod.
'''
